CREATE DATABASE RENTEE
  CHARACTER SET = UTF8;

use RENTEE;

CREATE TABLE `MD_BUILDING_TYPE` (
  `ID`       BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME`     VARCHAR(55)
             CHARACTER SET UTF8 DEFAULT NULL,
  `ORDERING` INT(2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE =INNODB
  AUTO_INCREMENT =1000
  DEFAULT CHARSET =UTF8
  COLLATE =UTF8_ROMANIAN_CI;

CREATE TABLE `MD_HEAT_SOURCE` (
  `ID`       BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME`     VARCHAR(55)
             CHARACTER SET UTF8 DEFAULT NULL,
  `ORDERING` INT(2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE =INNODB
  AUTO_INCREMENT =1000
  DEFAULT CHARSET =UTF8
  COLLATE =UTF8_ROMANIAN_CI;

CREATE TABLE `MD_CITY` (
  `ID`       BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME`     VARCHAR(55)
             CHARACTER SET UTF8 DEFAULT NULL,
  `ORDERING` INT(2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE =INNODB
  AUTO_INCREMENT =1000
  DEFAULT CHARSET =UTF8
  COLLATE =UTF8_ROMANIAN_CI;

CREATE TABLE `MD_NEIGHBORHOOD` (
  `ID`      BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME`    VARCHAR(55)
            CHARACTER SET UTF8 DEFAULT NULL,
  `CITY_ID` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_MD_NEIGHBORHOOD_CITY_ID` (`CITY_ID`),
  CONSTRAINT `FK_MD_NEIGHBORHOOD_CITY_ID` FOREIGN KEY (`CITY_ID`) REFERENCES `MD_CITY` (`ID`)
)
  ENGINE =INNODB
  AUTO_INCREMENT =1000
  DEFAULT CHARSET =UTF8
  COLLATE =UTF8_ROMANIAN_CI;

CREATE TABLE `RT_ADDRESS` (
  `ID`     BIGINT(20) NOT NULL AUTO_INCREMENT,
  `AP`     VARCHAR(10)
           CHARACTER SET UTF8 DEFAULT NULL,
  `BLOC`   VARCHAR(10)
           CHARACTER SET UTF8 DEFAULT NULL,
  `CP`     VARCHAR(10)
           CHARACTER SET UTF8 DEFAULT NULL,
  `ET`     VARCHAR(5)
           CHARACTER SET UTF8 DEFAULT NULL,
  `NR`     VARCHAR(5)
           CHARACTER SET UTF8 DEFAULT NULL,
  `SC`     VARCHAR(5)
           CHARACTER SET UTF8 DEFAULT NULL,
  `STREET` VARCHAR(50)
           CHARACTER SET UTF8 DEFAULT NULL,
  `CITYID` BIGINT(20) DEFAULT NULL,
  `NBHID`  BIGINT(20) DEFAULT NULL,
  `LAT`    DECIMAL(10, 7) DEFAULT NULL,
  `LNG`    DECIMAL(10, 7) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_RT_ADDRESS_CITYID` (`CITYID`),
  KEY `FK_RT_ADDRESS_NBHID` (`NBHID`),
  CONSTRAINT `FK_RT_ADDRESS_CITYID` FOREIGN KEY (`CITYID`) REFERENCES `MD_CITY` (`ID`),
  CONSTRAINT `FK_RT_ADDRESS_NBHID` FOREIGN KEY (`NBHID`) REFERENCES `MD_NEIGHBORHOOD` (`ID`)
)
  ENGINE =INNODB
  AUTO_INCREMENT =1000
  DEFAULT CHARSET =UTF8
  COLLATE =UTF8_ROMANIAN_CI;

CREATE TABLE `RT_INFO` (
  `ID`         BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FURNISHED`  TINYINT(1) DEFAULT '0',
  `MAXPERSONS` INT(2) DEFAULT NULL,
  `NOBATHS`    INT(2) DEFAULT NULL,
  `NOROOMS`    INT(2) DEFAULT NULL,
  `SQRM`       DECIMAL(10, 3) DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE =INNODB
  AUTO_INCREMENT =6
  DEFAULT CHARSET =UTF8
  COLLATE =UTF8_ROMANIAN_CI;

CREATE TABLE `RT_INTERVAL` (
  `ID`             BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FROMDATE`       DATE DEFAULT NULL,
  `FROMNOW`        TINYINT(1) DEFAULT '0',
  `UNTILDATE`      DATE DEFAULT NULL,
  `UNTILUNDEFINED` TINYINT(1) DEFAULT '0',
  PRIMARY KEY (`ID`)
)
  ENGINE =INNODB
  AUTO_INCREMENT =1000
  DEFAULT CHARSET =UTF8
  COLLATE =UTF8_ROMANIAN_CI;

CREATE TABLE `TRACERS` (
  `ID`         BIGINT(20) NOT NULL AUTO_INCREMENT,
  `IP`         BIGINT(20) DEFAULT NULL,
  `USER`       VARCHAR(50) DEFAULT NULL,
  `URL`        INT(11) DEFAULT NULL,
  `CITY`       INT(11) DEFAULT NULL,
  `NBH`        INT(11) DEFAULT NULL,
  `PRICEMIN`   DECIMAL(10, 2) DEFAULT NULL,
  `PRICEMAX`   DECIMAL(10, 2) DEFAULT NULL,
  `CREATEDATE` DATE DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE =MYISAM
  AUTO_INCREMENT =100
  DEFAULT CHARSET =LATIN1;

CREATE TABLE `USERS` (
  `ID`           BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CONFIRMED_BL` TINYINT(1) DEFAULT '0',
  `EMAIL`        VARCHAR(50) DEFAULT NULL,
  `NAME`         VARCHAR(50)
                 CHARACTER SET UTF8 DEFAULT NULL,
  `PASSWORD`     VARCHAR(50) DEFAULT NULL,
  `PHONE`        VARCHAR(20) DEFAULT NULL,
  `PHONE2`       VARCHAR(20) DEFAULT NULL,
  `PHONE3`       VARCHAR(20) DEFAULT NULL,
  `REGTOKEN`     VARCHAR(60) DEFAULT NULL,
  `ROLE`         VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EMAIL` (`EMAIL`)
)
  ENGINE =INNODB
  AUTO_INCREMENT =1000
  DEFAULT CHARSET =UTF8
  COLLATE =UTF8_ROMANIAN_CI;

CREATE TABLE `RT_ADVERT` (
  `ID`               BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ADTYPE`           VARCHAR(255) DEFAULT NULL,
  `DESCRIPTION`      VARCHAR(255) DEFAULT NULL,
  `DOTARI`           BIGINT(20) DEFAULT NULL,
  `PRIVATE_OWNED_BL` TINYINT(1) DEFAULT '0',
  `STATUS`           VARCHAR(255) DEFAULT NULL,
  `STATUSUPDATE`     DATE DEFAULT NULL,
  `BUILDINGTYPEID`   BIGINT(20) DEFAULT NULL,
  `ADUSR`            BIGINT(20) DEFAULT NULL,
  `ADDRESSID`        BIGINT(20) DEFAULT NULL,
  `INFOID`           BIGINT(20) DEFAULT NULL,
  `INTERVALID`       BIGINT(20) DEFAULT NULL,
  `CURRENCY`         VARCHAR(4) DEFAULT NULL,
  `DEPOSIT`          DECIMAL(11, 2) DEFAULT NULL,
  `NEGOTIABLE`       TINYINT(1) DEFAULT '0',
  `VALUE`            DECIMAL(11, 2) DEFAULT NULL,
  `WITHPICTURES`     TINYINT(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `FK_RT_ADVERT_ADUSR` (`ADUSR`),
  KEY `FK_RT_ADVERT_BUILDINGTYPEID` (`BUILDINGTYPEID`),
  KEY `FK_RT_ADVERT_ADDRESSID` (`ADDRESSID`),
  KEY `FK_RT_ADVERT_INFOID` (`INFOID`),
  KEY `FK_RT_ADVERT_INTERVALID` (`INTERVALID`),
  CONSTRAINT `FK_RT_ADVERT_ADDRESSID` FOREIGN KEY (`ADDRESSID`) REFERENCES `RT_ADDRESS` (`ID`),
  CONSTRAINT `FK_RT_ADVERT_ADUSR` FOREIGN KEY (`ADUSR`) REFERENCES `USERS` (`ID`),
  CONSTRAINT `FK_RT_ADVERT_BUILDINGTYPEID` FOREIGN KEY (`BUILDINGTYPEID`) REFERENCES `MD_BUILDING_TYPE` (`ID`),
  CONSTRAINT `FK_RT_ADVERT_INFOID` FOREIGN KEY (`INFOID`) REFERENCES `RT_INFO` (`ID`),
  CONSTRAINT `FK_RT_ADVERT_INTERVALID` FOREIGN KEY (`INTERVALID`) REFERENCES `RT_INTERVAL` (`ID`)
)
  ENGINE =INNODB
  AUTO_INCREMENT =1000
  DEFAULT CHARSET =UTF8
  COLLATE =UTF8_ROMANIAN_CI;

CREATE TABLE `RT_IMAGE` (
  `ID`           BIGINT(20) NOT NULL AUTO_INCREMENT,
  `BYTES`        BIGINT(20) DEFAULT NULL,
  `CREATEDAT`    DATE DEFAULT NULL,
  `ETAG`         VARCHAR(255) DEFAULT NULL,
  `FORMAT`       VARCHAR(50) DEFAULT NULL,
  `HEIGHT`       BIGINT(6) DEFAULT NULL,
  `PUBLICID`     VARCHAR(255) DEFAULT NULL,
  `RESOURCETYPE` VARCHAR(255) DEFAULT NULL,
  `SECUREURL`    VARCHAR(255) DEFAULT NULL,
  `SIGNATURE`    VARCHAR(255) DEFAULT NULL,
  `TYPE`         VARCHAR(50) DEFAULT NULL,
  `URL`          VARCHAR(255) DEFAULT NULL,
  `URLSMALL`     VARCHAR(255) DEFAULT NULL,
  `VERSION`      BIGINT(10) DEFAULT NULL,
  `WIDTH`        BIGINT(6) DEFAULT NULL,
  `ADVERTID`     BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_RT_IMAGE_ADVERTID` (`ADVERTID`),
  CONSTRAINT `FK_RT_IMAGE_ADVERTID` FOREIGN KEY (`ADVERTID`) REFERENCES `RT_ADVERT` (`ID`)
)
  ENGINE =INNODB
  AUTO_INCREMENT =1000
  DEFAULT CHARSET =LATIN1;

CREATE TABLE `RT_ESTIMATED_UNIT` (
  `ID`        BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CURRENCY`  VARCHAR(3) DEFAULT NULL,
  `FROMDATE`  DATE DEFAULT NULL,
  `NAME`      VARCHAR(100) DEFAULT NULL,
  `TODATE`    DATE DEFAULT NULL,
  `VALUE`     DECIMAL(15, 3) DEFAULT NULL,
  `ADVERT_ID` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_RT_ESTIMATED_UNIT_ADVERT_ID` (`ADVERT_ID`),
  CONSTRAINT `FK_RT_ESTIMATED_UNIT_ADVERT_ID` FOREIGN KEY (`ADVERT_ID`) REFERENCES `RT_ADVERT` (`ID`)
)
  ENGINE =INNODB
  AUTO_INCREMENT =1000
  DEFAULT CHARSET =UTF8
  COLLATE =UTF8_ROMANIAN_CI;


CREATE TABLE `RT_FAVORITES` (
  `ID`          BIGINT(20) NOT NULL AUTO_INCREMENT,
  `DATECREATED` DATETIME DEFAULT NULL,
  `ADVERTID`    BIGINT(20) DEFAULT NULL,
  `USERID`      BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_RT_FAVORITES_ADVERTID` (`ADVERTID`),
  KEY `FK_RT_FAVORITES_USERID` (`USERID`),
  CONSTRAINT `FK_RT_FAVORITES_ADVERTID` FOREIGN KEY (`ADVERTID`) REFERENCES `RT_ADVERT` (`ID`),
  CONSTRAINT `FK_RT_FAVORITES_USERID` FOREIGN KEY (`USERID`) REFERENCES `USERS` (`ID`)
)
  ENGINE =INNODB
  AUTO_INCREMENT =1000
  DEFAULT CHARSET =LATIN1;

